# Top-level configuration
name = "preview-gen"
main = "src/index.ts"
compatibility_date = "2025-01-24"
observability.enabled = true

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "imgshare"
preview_bucket_name="imgshare"